homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 21.0333
  longitude: 105.85
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 20
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Ho_Chi_Minh

  customize:
    switch.ventilators:
      icon: mdi:fan
    light.garage_ceiling_light:
      icon: mdi:lightbulb
    light.garage_outside_light:
      icon: mdi:spotlight
    sensor.temperature:
      icon: mdi:temperature-celsius
    sensor.humidity:
      icon: mdi:water-percent
# # Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
# sensor:
#   platform: yr

#### our config
# mqtt conection
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  
sensor temperature:
  - platform: mqtt
    name: "temperature"
    state_topic: "/bedroom/temperature/status"

sensor humidity:
  - platform: mqtt
    name: "humidity"
    state_topic: "/bedroom/humidity/status"

sensor:
  - platform: worldclock
    time_zone: Asia/Ho_Chi_Minh

switch one:
  platform: mqtt
  name: "Ventilators"
  state_topic: "/garage/ventilators/status"
  command_topic: "/garage/ventilators/set"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  optimistic: true

light two:
  platform: mqtt
  name: "Garage outside light"
  state_topic: "/garage/outside_light/status"
  command_topic: "/garage/outside_light/switch"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  optimistic: true

light three:
  platform: mqtt
  name: "Garage ceiling light"
  state_topic: "/garage/ceiling_light/status"
  command_topic: "/garage/ceiling_light/switch"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  optimistic: true

cover:
  platform: mqtt
  name: "MQTT Cover"
  state_topic: "home-assistant/cover"
  command_topic: "home-assistant/cover/set"
  retain: true
  optimistic: true

group:
  Garage:
    - sensor.temperature
    - sensor.humidity
    - switch.ventilators
    - light.garage_ceiling_light
    - light.garage_outside_light
    - cover.mqtt_cover