homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 21.0333
  longitude: 105.85
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 20
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Ho_Chi_Minh

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
# sensor:
#   platform: yr

#### our config
# mqtt conection
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  
sensor:
  - platform: mqtt
    name: "Fabian's Mood"
    state_topic: "home-assistant/fabian/mood"

# Example configuration.yml entry
switch:
  platform: mqtt
  name: "Bedroom Switch"
  state_topic: "home/bedroom/switch"
  command_topic: "home/bedroom/switch/set"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
  optimistic: true
